### ISSUE TITLE
Add element to schema indicating the recorder has a serial interface

### ISSUE THREAD

**Issue by StokesMIDE** [MideTechnology/idelib#110]
Note: This is primarily a firmware thing, but `idelib` contains the canonical copy of the `mide_ide.xml` schema.

Devices that support a serial command interface should announce this in their `DEVINFO` file. Proposed is a child element of `<RecorderInfo>` to indicate this:

```xml
<MasterElement name="SerialCommandInterface" id="0x5230" multiple="0" mandatory="0">Present in the device's DEVINFO if it supports control via serial</MasterElement>
```

The 0x5230-0x523F range of EBML IDs would be reserved for different interfaces we might introduce in the future. They are primarily 'marker' elements (i.e., they are typically empty and their presence alone is the indicator), but future development could add additional information as child elements (names and IDs TBD).

**Comment by pscheidler** [comment]
Done in #111
