### ISSUE TITLE
`EventArray.iterMinMeanMax()` + `UnivariatePolynomial` has problems

### ISSUE THREAD

**Issue by StokesMIDE** [MideTechnology/idelib#119]
Somewhere in the process of iterating `EventArray.iterMinMeanMax()` with a `PolyPoly` transform containing a `UnivariatePolynomal`, the data is retrieved as the wrong shape. 

```python-traceback
Traceback (most recent call last):
  ... (irrelevant calls from code using idelib removed) ...
  File "<project venv>\lib\site-packages\idelib\dataset.py", line 2115, in iterMinMeanMax
    mx = xform(t, m, session, noBivariates=self.noBivariates)
  File "<project venv>\idelib\transforms.py", line 1347, in __call__
    return timestamp, self._function(*values)
TypeError: <lambda>() takes 2 positional arguments but 57 were given
```
The shape of `values` in the above case was `(57,)` .

`EventArray._getBlockRollingMean()` may be the source of the weird data. I'm attempting to pinpoint the problem more specifically.

The introduction of the 'in place' optimizations (3.2) seem to be where this came in. @theflanman, I know this is no longer your problem, but does this ring any bells?

**Comment by theflanman** [comment]
It's definitely ringing a bell.  IIRC, there was a bug I couldn't track down and we decided to deprecate rolling mean removal in favor of an IIR or FIR filter.

**Comment by StokesMIDE** [comment]
@theflanman Rolling mean removal is deprecated; the method generates a warning and just does total mean.

**Comment by pscheidler** [comment]
#135 and #136 appear to test for these issues and fix this.
