### ISSUE TITLE
`EventArray.getInterval()` returning wrong end time

### ISSUE THREAD

**Issue by StokesMIDE** [MideTechnology/idelib#24]
From issue https://github.com/MideTechnology/SlamStickLab/issues/333: in enDAQ Lab 2.0 and later, `getInterval()` is reporting the end prematurely. This is possibly related to how the Lab is using `idelib`, but it shouldn't be happening in any case.

From the SlamStickLab repo issue:

> 1. Load an IDE longer than 10000000 samples (or whatever the 'Pre-Plotting Samples' is configured in the app preferences), so it will plot while continuing to load.
> 2. Zoom out (e.g. right-click).
> 3. The 'end of recording' gray area starts too early, apparently at what was the right side of the initial plot.
> 
> It seems like `idelib.dataset.EventArray.getInterval()` is returning incorrect values, at least where it's being used in the Lab's `plots.PlotCanvas._OnDraw()` (or `render()` in the Python 3 branch).
> 
> Confirmed to occur in Lab 2.0 and later.
> 
> This is probably an `idelib` bug, but easily repeatable in the Lab.

**Comment by CrepeGoat** [comment]
addressed in #28, #25 -> @StokesMIDE should be ready to close
