### ISSUE TITLE
Helper Functions

### ISSUE THREAD

**Issue by pscheidler** [MideTechnology/idelib#3]
Since we'd like this to be accessible, can we include helper functions such as:
 - get_sensor_name(subchannel) - return subchannel.sensor.name
 - get_channel_id(subchannel) - return subchannel.parent.id

**Comment by StokesMIDE** [comment]
@pscheidler It seems like the new `endaq.*` libraries serve this need; can this be closed?

**Comment by StokesMIDE** [comment]
I think `endaq-python` takes care of this. Closing.
