### ISSUE TITLE
Revert #13

### ISSUE THREAD

**Issue by CrepeGoat** [MideTechnology/idelib#31]
I have some concerns about #12 and the resulting PR #13 re: allowing non-integer indices for EventArray objects. originally discussed in #12; my remarks copied below for convenience:

1) for consistency with lists and numpy arrays (neither support float indices),
2) so that users (which we have now I guess) don't mis-assume that they're indexing on *timestamps* instead of integer sample numbers, and
3) because any prior errors that prompted this change originally may be indicative of something wrong in the corresponding index calculations, which should be fixed but are now hidden.

**Comment by CrepeGoat** [comment]
@CFlaniganMide's comments, for convenience:

> 1. There's plans to make them compatible, as part of the NRE project category.  I'll be working on that shortly after tow tester wraps (hopefully before those plans have time to change).
> 2. Agreed, timestamps shouldn't use the bracket indexing format.  Hopefully if we can get everything running as a numpy array, then we can just toss it at a numpy interpolate routine. 
> 3. It's true, but like I said, not sure what the cause is.  Setting warnings before reverting changes might help us locate issues before we start working on them.

**Comment by CFlaniganMide** [comment]
@CrepeGoat was this successfully closed in #36 ?

**Comment by CFlaniganMide** [comment]
huh, weird.  Well, it's closed now.
