### ISSUE TITLE
`Channel` objects no longer hashable

### ISSUE THREAD

**Issue by CrepeGoat** [MideTechnology/idelib#58]
From [@StokesMIDE's original comment](https://github.com/MideTechnology/SlamStickLab/pull/372#issuecomment-880196647):

> It's a side-effect of the idelib port to Python 3. It isn't obvious where it is occurring. It's an idelib issue, though, and isn't worth investigating at the moment.

This isn't a huge issue, but results in errors when trying to use `Channel` objects in `set`s and as keys in `dict`s, which is occasionally used in other code bases.

**Comment by StokesMIDE** [comment]
It may be that implementing `__eq__()` is what did it. The rules (or at least best practices) regarding `__hash__()` and `__eq__()` have changed in Python 3.

**Comment by StokesMIDE** [comment]
I'm assuming this is closed now. Can I get confirmation?

**Comment by CrepeGoat** [comment]
It looks like 69147643eb1a7f3ff5580fe97778e40b50460c94 was never merged into dev, so I think this is still open
