### ISSUE TITLE
Move EventList functionality into EventArray

### ISSUE THREAD

**Issue by StokesMIDE** [MideTechnology/idelib#6]
The old `EventList` is basically obsolete; it's not instantiated any longer. Its functionality should just be moved into the `EventArray` subclass (or probably the other way around, since there's much more in `EventList`). The hacks in `importer` and `parsers` that make them use `EventArray` should be removed/refactored as well.

**Comment by CFlaniganMide** [comment]
#42 should have fully addressed this, can we close it?
