### ISSUE TITLE
CD Pipeline

### ISSUE THREAD

**Issue by CFlaniganMide** [MideTechnology/idelib#9]
Travis-ci has some powerful tools for Continuous Deployment of builds and packages.  This would save a pretty decent amount of time whenever we would manually deploy a build.

There's an official article [here](https://docs.travis-ci.com/user/deployment/pypi/) describing the process.

We need to decide how to trigger builds:
- On tag generation, which should always be created when completing a release with the gitflow plugin
- On every commit to master.

There's no build artifacts to consider, which makes things easier.

**Comment by CFlaniganMide** [comment]
Following gitflow properly, every commit to master should be a release, which would work best if we only want to upload releases.  

Another strategy suggests these rules:
- build and upload on tags
- commits into master are tagged with a release version
  - this can include a post-release for non-code fixes, such as documentation typos
- On a release branch, release candidates can be tagged to build and upload
- On the development branch, alpha or beta releases can be tagged
- Post release builds would probably be treated the same as releases, since the actual code should never change, only documentation.
- We don't do dev builds, really, but if we wanted, they should go in feature branches.

The second strategy allows for easier deployment of partial fixes to users who request them before an official release.  

All these considerations are also relevant to our other repos, such as ebmlite.

**Comment by CFlaniganMide** [comment]
@StokesMIDE what do you think?

**Comment by StokesMIDE** [comment]
Would we ever release alpha/beta versions to PyPI? I'm not clear on the details of how it handles multiple versions.

**Comment by CFlaniganMide** [comment]
I looked it up, anything that doesn't fit the full release or post release pattern is labeled as pre-release.  When you run install, by default it ignores pre-release unless there are only pre-release builds.  

So we have 3.0.0rc1 up, which is marked as pre-release.  Since it's the only one, when you install idelib, that's what you install.  When we release 3.0.0, then that's what will install, and if we release 3.0.0.post1 with, say, documentation updates, that will install instead.  

Then, if we put up 3.0.1b1, that's a pre-release, and pip will install 3.0.0.post1.  Unless you specify --pre as an argument in pip, then it will just be the latest build of any kind.
